# expr_sim.R

#' Expression Similarity.
#'
#' \code{expr_sim.R} Calculate the pairwise similarity of gene expression profiles.
#'
#' Similarity between 2 expression profiles is calculated by taking the absolute value of the Sprearman correlation. Spearman correlation is used because we do not care whether the correlation is linear. Absolute value ensures that both strong positive and negative correlations result in high similarity.
#' @section <title>: additional explanation
#'
#' @param gene1 Character, HGNC symbol of the first gene.
#' @param gene2 Character, HGNC sysmbol of the second gene
#' @param profiles Matrix of expression profiles, generated by loading "http://steipe.biochemistry.utoronto.ca/abc/assets/GEO-QN-profile-2019-03-24.rds"
#' @return Numeric, similarity score: the absolute value of the spearman correlation of the expression profiles of gene1 and gene2. Or NA if the expression profile for that gene is unavailable.
#'
#' @family <optional description of family>
#'
#' @author \href{https://orcid.org/0000-0001-5724-2252}{Rachel Silverstein} (aut)
#'
#' @seealso \code{\link{<function>}} <describe related function>, ... .
#'
#' @examples
#' # Find the similarity in the expression profiles of BRCA1 and FANCI
#' expr_sim("BRCA1", "FANCI")
#' # [1] 0.2387499
#'
#' @export

expr_sim <- function(gene1, gene2, profiles=exprofs) {
  prof1 <- profiles[gene1,]
  prof2 <- profiles[gene2,]
  similarity <- abs(cor(x = prof1, y = prof2, method = "spearman", use = "na.or.complete"))
  return(similarity)
}

# [END]
