# expr_dist.R

#' Expression Distance.
#'
#' \code{expr_dist} calculates the pairwise distance of gene expression profiles.
#'
#' distance between 2 expression profiles is calculated by taking the absolute
#' value of the Spearman correlation. Spearman correlation is used because we do
#' not care whether the correlation is linear. Absolute value ensures that both strong
#' positive and negative correlations result in high distance.
#'
#' @param gene1 Character, HGNC symbol of the first gene.
#' @param gene2 Character, HGNC sysmbol of the second gene
#' @param profiles Matrix of expression profiles, generated by calling
#' fetchData("GEOprofiles")
#' @return Numeric, distance score: the absolute value of the spearman
#' correlation of the expression profiles of gene1 and gene2. Distance is
#' returned as 1 if the expression profile for either of the genes is unavailable.
#'
#'
#' @author \href{https://orcid.org/0000-0001-5724-2252}{Rachel Silverstein} (aut)
#'
#' @seealso \code{\link{fetchData}} for the format of expression profiles used by
#' this function.
#'
#' @examples
#' # Find the distance in the expression profiles of BRCA1 and BRCA2
#' GEO <- fetchData("GEOprofiles")
#' expr_dist("BRCA1", "BRCA2", GEO)
#'
#'
#' @export

expr_dist <- function(gene1, gene2, profiles) {
  prof1 <- profiles[gene1,]
  prof2 <- profiles[gene2,]
  similarity <- abs(stats::cor(x = prof1,
                               y = prof2,
                               method = "spearman",
                               use = "na.or.complete"))
  if (is.na(similarity)) {
    similarity <- 0
  }
  distance <- 1 - similarity
  return(distance)
}

# [END]
