# stub function taken from Dr. Steipe's BCB420.2019.ESA package
# Helpers

bioSystems <- c("PHALY", "SLIGR", "NLRIN")

geoQNURL <- paste0(
  "http://steipe.biochemistry.utoronto.ca/abc/assets/",
  "GEO-QN-profile-2019-03-24.rds"
)
dfColNames <- c("gene1", "gene2", "correlation", "goCorrelation")

#'
#' Helper function for the correlation and semantic corellation graphs
#' @param fileName - if not NULL - it will use the Cairo package to create a
#' device. It checks the file extension to instantiate appropriate device;
#' otherwise - it does nothing (graphs are plotted on screen)
#' @return none
#' @author \href{https://orcid.org/0000-0002-8778-6442}{Denitsa Vasileva} (aut)
#' @references https://CRAN.R-project.org/package=Cairo
preDraw <- function(fileName) {
  if (is.null(fileName)) {
    return()
  }
  # is the file extension pdf?
  if (grepl(".pdf$", fileName)) {
    Cairo::CairoPDF(
      file = fileName,
      width = 1920,
      height = 1080,
      res = 92,
      pointsize = 12
    )
    return()
  }
  # otherwise - default to png
  if (!grepl(".png$", fileName)) {
    fileName <- paste0(fileName, ".png")
  }
  # Cairo Package https://CRAN.R-project.org/package=Cairo
  Cairo::CairoPNG(
    file = fileName,
    width = 1920,
    height = 1080,
    res = 92,
    pointsize = 12
  )
}

#'
#' Helper function for the correlation & semantic correlation graphs
#' @param fileName - if not NULL - it will call dev.off to save the file
#' otherwise - it prompts for user input - so the user can see the graph
#' before the next one is drawn
#' @return none
#' @author \href{https://orcid.org/0000-0002-8778-6442}{Denitsa Vasileva} (aut)
postDraw <- function(fileName) {
  if (is.null(fileName)) {
    readline(prompt = "Press enter to continue...")
  } else {
    dev.off()
  }
}

#'
#' \code{computeCorrelations()} Calculates Semantic similarity and Correlation
#' between expression profiles of pairwise genes and returns a
#' data.frame
#'
#' @author \href{https://orcid.org/0000-0002-8778-6442}{Denitsa Vasileva} (aut)
#' @param silent = FALSE - suppresses all messages when TRUE
#' @return a data.frame containing gene A, gene B, correlation between them and
#' GOSemSim correlation
#'
computeCorrelations <- function(silent = FALSE) {
  sysDB <- fetchData("SysDB")
  geoQNXP <- readRDS(url(geoQNURL))

  if (!silent) {
    cat(sprintf("Loading GO - genome wide annotation for human.\n"))
  }
  hsGO <- GOSemSim::godata("org.Hs.eg.db", keytype = "SYMBOL", ont = "MF")
  if (!silent) {
    cat(sprintf("%d rows loaded.\n", nrow(hsGO)))
  }
  systemV <- vector(mode = "character", length = 0)
  gene1V <- vector(mode = "character", length = 0)
  gene2V <- vector(mode = "character", length = 0)
  correlationV <- vector(mode = "numeric", length = 0)
  goCorrelationV <- vector(mode = "numeric", length = 0)
  for (bioSystem in bioSystems) {
    systemComponents <- SyDBgetSysSymbols(sysDB, bioSystem)[[1]]
    componentsCount <- length(systemComponents)
    if (!silent) {
      cat(sprintf("\nComputing correlations between %s genes:", bioSystem))
    }
    for (c1 in 1:componentsCount) {
      for (c2 in c1:componentsCount) {
        gene1 <- systemComponents[c1]
        gene2 <- systemComponents[c2]
        if (c1 != c2) {
          prf1 <- as.numeric(geoQNXP[gene1, ])
          prf2 <- as.numeric(geoQNXP[gene2, ])
          cCorr <- cor(prf1, prf2, use = "pairwise.complete.obs")
          cGO <- GOSemSim::geneSim(gene1,
            gene2,
            semData = hsGO,
            measure = "Wang",
            combine = "BMA"
          )[[1]]
        } else { # the same gene
          cCorr <- 1
          cGO <- 1
        }
        gene1V <- c(gene1V, gene1)
        gene2V <- c(gene2V, gene2)
        correlationV <- c(correlationV, cCorr)
        goCorrelationV <- c(goCorrelationV, cGO)
        systemV <- c(systemV, bioSystem)
      }
      if (!silent) {
        cat(sprintf("."))
      }
    }
  }
  if (!silent) {
    cat(sprintf("\n"))
  }

  df <- data.frame(systemV, gene1V, gene2V, correlationV, goCorrelationV)
  colnames(df) <- c("System", dfColNames)
  return(df)
}

#'
#' Calculates statistics for the test case. The test case is designed to
#' calculate the data correctness in the data.frame generated by
#' computeCorrelations(). This helper counts the records in the
#' DF that belong to bioSys and sums-up the correlation and
#' semantic simulation columns.
#' Those values are later compared in the test cases with pre-calculated values
#' @author \href{https://orcid.org/0000-0002-8778-6442}{Denitsa Vasileva} (aut)
#' @param dframe - the source data frame
#' @param bioSys - name of the system (PHALY, SLIGR or NLRIN)
#' @return a list which contains record counts, control sum of the correlation
#' and sem sim correlation for all records that belong to a System
#' in the data frame
calcStats <- function(dframe, bioSys) {
  d <- dframe[dframe$System == bioSys, ]
  corrSum <- sum(d$correlation, na.rm = TRUE)
  goCorrSum <- sum(d$goCorrelation, na.rm = TRUE)
  recCount <- nrow(d)
  return(list(recCount = recCount, corrSum = corrSum, goCorrSum = goCorrSum))
}

#'
#' \code{plotCorrelations()} Calculates Semantic similarity and Correlation
#' between expression profiles of pairwise
#' genes and returns a list of two heat maps representing the two correlation
#' levels and one plot to charcaterize the orthogonal relationship
#' between genes in the system.
#'
#'
#' @param bioSys Biological system symbol.
#' @param coExpFile - if specified - will save the functional correlation
#' graph to file. Supported file formats - pdf and png
#' @param semSimFile - if specified - will dave the semantic similarity
#' correlation graph to file. Supported formats - pdf and png
#' @param  coExpVsSemFile - if sepcified - will save the functional correlation
#' vs semantic similarity correlation to file. Supported formats - see ggsave.
#' @param  pShape - shape of the points in the functional vs co-expression
#' graph. Example values - 1,16,22,23 etc. See ggplot.
#' @return ggplot graph (list).
#'
#' @author \href{https://orcid.org/0000-0002-8778-6442}{Denitsa Vasileva} (aut)
#'
#' @examples
#' plotCorrelations("PHALY") ## plots functional correlation graph, semantic
#' ## similarity correlation graph and functional vs co-expression correlation
#' ## graphs and returns the latter as ggplot list
#'
#'
#' plotCorrelations("PHALY", coExpFile = "somefile.pdf") ## save functional
#' ## correlation graph into file 'somefile.pdf', and plots similarity correlation
#' ## graph and functional vs co-expression correlation graphs and returns the
#' ## latter as ggplot list
#' @export
plotCorrelations <- function(bioSys,
                             coExpFile = NULL,
                             semSimFile = NULL,
                             coExpVsSemFile = NULL,
                             pShape = 16) {
  sdf <- computeCorrelations()
  if (!bioSys %in% sdf$System) {
    stop("Unknown system passed as parameter.")
  }

  # Convert the data frame to a symmetrix matrix (required by corrplot)
  sysDF <- sdf[
    sdf$System == bioSys,
    c("gene1", "gene2", "correlation", "goCorrelation")
  ]

  geneCount <- length(unique(sysDF$gene1))
  coM <- matrix(nrow = geneCount, ncol = geneCount)
  goM <- matrix(nrow = geneCount, ncol = geneCount)
  colnames(coM) <- unique(sysDF$gene1)
  rownames(coM) <- unique(sysDF$gene2)
  colnames(goM) <- unique(sysDF$gene1)
  rownames(goM) <- unique(sysDF$gene2)
  for (i in 1:nrow(sysDF)) {
    coM[
      as.character(sysDF$gene1[i]),
      as.character(sysDF$gene2[i])
    ] <- as.numeric(sysDF$correlation[i])
    coM[
      as.character(sysDF$gene2[i]),
      as.character(sysDF$gene1[i])
    ] <- as.numeric(sysDF$correlation[i])
    goM[
      as.character(sysDF$gene1[i]),
      as.character(sysDF$gene2[i])
    ] <- as.numeric(sysDF$goCorrelation[i])
    goM[
      as.character(sysDF$gene2[i]),
      as.character(sysDF$gene1[i])
    ] <- as.numeric(sysDF$goCorrelation[i])
  }
  # R requires Cairo package - in order to save the image to file
  # Check if the package is installed and if not - default to screen
  if (!"Cairo" %in% rownames(installed.packages())) {
    if (!is.null(coExpFile) || !is.null(semSimFile) || !is.null(coExpVsSemFile)) {
      message("Saving graphs to file requires Cairo pckg. Defaulting to screen.")
      coExpFile <- NULL
      semSimFile <- NULL
      coExpVsSemFile <- NULL
    }
  }

  # Plot the correlation in a file (if file name specified)
  # otherwsie - plot to R Console's canvas
  cat(sprintf("Plotting functional correlation...\n"))
  preDraw(coExpFile)
  corrplot::corrplot(as.matrix(coM),
    type = "upper",
    order = "original",
    tl.cex = 0.5,
    diag = TRUE,
    title = "Functional Correlation",
    col = RColorBrewer::brewer.pal(n = 8, name = "RdYlBu"),
    mar = c(0, 0, 1, 0)
  )
  postDraw(coExpFile)

  # Plot the correlation in a file (if file name specified)
  # otherwsie - plot to R Console's canvas
  cat(sprintf("Plotting semantic similarity correlation...\n"))
  preDraw(semSimFile)
  corrplot::corrplot(goM,
    type = "upper",
    order = "original",
    tl.cex = 0.5,
    diag = TRUE,
    na.label = "N",
    na.label.col = "white",
    title = "Semantic similarity correlation",
    col = RColorBrewer::brewer.pal(n = 8, name = "RdYlBu"),
    mar = c(0, 0, 1, 0)
  )
  postDraw(semSimFile)

  cat(sprintf("Plotting functional vs co-expression correlation...\n"))
  title <- paste0("Functional vs co-expression correlation ", bioSys)
  cols <- c("PHALY" = "darkgrey", "SLIGR" = "grey", "NLRIN" = "grey")
  cols[bioSys] <- "darkgreen"

  sdf$ord <- ifelse(sdf$System == bioSys, 2.5, 1.5)
  sdf <- sdf[order(sdf$ord), ]

  graph <- ggplot2::ggplot(data = sdf) +
    ggplot2::geom_point(
      ggplot2::aes(x = goCorrelation, y = correlation, colour = System),
      shape = pShape, # 16, #1,
      size = 2.0,
      na.rm = TRUE
    ) +
    ggplot2::ggtitle(title) +
    ggplot2::theme_bw() +
    ggplot2::scale_color_manual(values = cols) +
    ggplot2::scale_x_continuous(name = "Semantic similarity") +
    ggplot2::scale_y_continuous(name = "Co-expression correlation")

  print(graph)

  if (!is.null(coExpVsSemFile)) {
    ggplot2::ggsave(filename = coExpVsSemFile)
  }
  return(graph)
}
